version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-resize-detector
    versions:
    - 5.2.0
    - 6.3.3
    - 6.5.0
    - 6.6.0
    - 6.6.1
    - 6.6.3
    - 6.6.4
    - 6.6.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
